import { PermissionKey } from './permissions.catalog';

export const ROLES = {
  name: 'Admin',
  description: 'Adminstrador do Sistema',
  permissionKeys: [
    // Usuários
    'core.user.create',
    'core.user.view',
    'core.user.update',
    'core.user.delete',
    'tenant.products.view',
    'tenant.products.create',
    'tenant.products.update',
    'tenant.products.delete',
    'tenant.payment-methods.view',
    'tenant.payment-methods.create',
    'tenant.payment-methods.update',
    'tenant.payment-methods.delete',
    'tenant.orders.view',
    'tenant.orders.create',
    'tenant.orders.update',
    'tenant.orders.delete',
    'tenant.brands.view',
    'tenant.brands.create',
    'tenant.brands.update',
    'tenant.brands.delete',
    'tenant.groups.view',
    'tenant.groups.create',
    'tenant.groups.update',
    'tenant.groups.delete',
    'tenant.clients.view',
    'tenant.clients.create',
    'tenant.clients.update',
    'tenant.clients.delete',
  ] satisfies readonly PermissionKey[],
};
